[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[parachains]]
id = 1000

[parachains.collator]
name = "bob"
ws_port = 9988
command = "parachain-template-node"
