name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/free-disk-space
      - if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/ubuntu-dependencies
      - if: contains(matrix.os, 'macos')
        uses: ./.github/actions/macos-dependencies

      - name: Build the template
        run: cargo build
        timeout-minutes: 90

      - name: Run clippy
        run: |
          SKIP_WASM_BUILD=1 cargo clippy --all-targets --locked --workspace --quiet
          SKIP_WASM_BUILD=1 cargo clippy --all-targets --all-features --locked --workspace --quiet
        timeout-minutes: 30

      - name: Run the tests
        run: SKIP_WASM_BUILD=1 cargo test
        timeout-minutes: 15

      - name: Build the docs
        run: SKIP_WASM_BUILD=1 cargo doc --workspace --no-deps
        timeout-minutes: 15

      # This test only makes sure the node got successfully built
      # and can be executed without issues on Ubuntu and macOS.
      # Check the `test-zombienet` workflow for a parachain smoke test.
      - name: Check that the node starts up
        run: |
          ./target/debug/parachain-template-node --help

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/free-disk-space

      - name: Build the Dockerfile
        run: docker build . -t polkadot-sdk-parachain-template
        timeout-minutes: 90
